### PR TITLE
don't run scons as part of setup

### PR DESCRIPTION
**Pull request by gabrielrussell**
setting up ninja via scons needs to be manual and documented specifically

### CODE REVIEW

**Comment by gabrielrussell** [comment]
I think that leaving the install ninja in is good as people will want to use it.

**Comment by guoyr** [comment]
> setting up ninja via scons needs to be manual and documented specifically

It looks like the [new wiki page for setting up Ubuntu 18.04 (internal)](https://wiki.corp.mongodb.com/display/HGTC/How+to+set+up+an+Ubuntu+workstation%3A+A+guide+for+the+lazy) has almost identical steps for creating `ninja.build`. Please remove these steps from the Ubuntu wiki page when merging this PR.

**Comment by gabrielrussell** [comment]
The instructions for ubuntu don't look similar to me. They produce a
ninja.build file via running scons, which is what I think it correct what
we want to tell the inters to do.

**Comment by guoyr** [comment]
> They produce a ninja.build file via running scons

What are you talking about? This tool literally uses the same scons invocation as the Ubuntu script to create `build.ninja`, minus the one Linux-only flag. The only difference is that this tool is in Python and the Ubuntu script is in bash.

**Comment by gabrielrussell** [comment]
Maybe it's better that we discuss this in person. I can swing by your desk
and chat for a moment if you like.

**Pull request merged**
